Implement an initial working version of the modified architecture workflow
bitcoinscalinglabs/bitcoin-ipc pull request #12
Opened 2024-07-19 12:39 UTC by OrestisAlpos

This is a draft PR, meant to provide feedback and suggestions, not to be merged yet.
It contains:
- Implement l1_manager binary that is responsible for handling L1 IPC commands
- Implement subnet_interactor binary that is responsible for handling L_i IPC commands where i > 1
- Implement ipc_subnet_state struct, that exposes an interface for child subnet interaction and holds the subnet state
- Introduce new directory `BTC` which describes the subnet hierarchy and each file holds the particular subnet state
- Update docs

2024-07-19 13:47 UTC, OrestisAlpos commented on src/ipc_subnet_state.rs
> +pub struct IPCSubnetState {
Let's break this state in two pieces: IpcState, SubnetState.
Everything in this file can go into the IpcState, except for the `create_account()`, `transfer()` and `get_checkpoint()` functions, which operate on the SubnetState.
Then we can have the L1 Manager use only IpcState, and the L2 Validator (Subnet Simulator) use only the SubnetState. I have now described the two entities in Notion in detail, so as to clear any confusion.

2024-07-19 13:47 UTC, OrestisAlpos commented on src/ipc_subnet_state.rs
> +    pub fn create_account(&mut self, address: &str, initial_balance: u64) {
This should be part of / used by the Subnet Simulator.

2024-07-19 13:47 UTC, OrestisAlpos commented on src/ipc_subnet_state.rs
> +    pub fn transfer(&mut self, from: &str, to: &str, amount: u64) -> Result<(), String> {
This should be part of / used by the Subnet Simulator.

2024-07-19 13:47 UTC, OrestisAlpos commented on src/ipc_subnet_state.rs
> +    pub fn get_checkpoint(&mut self) -> String {
This should be part of / used by the Subnet Simulator.

2024-07-19 13:47 UTC, OrestisAlpos commented on src/bin/subnet_interactor.rs
> +            println!("3. Add child subnet");
Let's remove this. We are not interested in creating children of L2 subnets. The only "create child" we care about is offered by the L1 Manager.

2024-07-19 13:47 UTC, OrestisAlpos commented on src/bin/subnet_interactor.rs
> +            println!("4. Checkpoint state");
I would suggest we remove that as well. Let's make the Relayer responsible for checkpoints.

2024-07-19 13:47 UTC, OrestisAlpos commented on BTC/B/B.json
> +{
This is very nice, let's keep this  structure of storing the IPC state. But, as stated elsewhere, let's remove from here everything that is subnet-internal (accounts and their balance) and everything about subnets of a subnet (we do not care about L3+).

2024-07-19 14:13 UTC, OrestisAlpos commented on src/bin/l1_manager.rs
> +        println!("Enter subnet url:");
The user should not have to input  this. The URL can be "BTC"/name.

2024-07-25 13:39 UTC, OrestisAlpos commented on src/bin/l1_manager.rs
> +        println!("Enter IP address:");
```suggestion
        println!("Enter your IP address:");
```

2024-07-25 13:39 UTC, OrestisAlpos commented on src/bin/l1_manager.rs
> +        let ipc_state = IPCState::load_state(format!(
Wouldn't it be better if this function loaded the state in the beginning and then asked the user which of the existing subnets it wants to join (the user can just type the subnet name and get an error if it doesn't exist)?

2024-07-25 13:39 UTC, OrestisAlpos commented on src/bin/l1_manager.rs
> +        println!("Enter public key:");
Is this  the public key of the validator in the subnet or the subnetPK? Currently it seems that we use it as both. If it is the validator subnet public key, then we should add it to the validator_data, and that's all. If it is used to identify the subnet to join, then we also need to ask the user for its validator public key (which btw will not be a bitcoin key but a format defined by the subnet, so it does not have to be parsed here, just included as a string or bytes).

2024-07-25 13:39 UTC, OrestisAlpos commented on src/main.rs
>  fn main() -> Result<(), Box<dyn std::error::Error>> {
@jakovmitrovski It looks like we do not need a main function anymore, as all functionality has been implemented in the binaries. If you agree, can you delete it completely?

2024-07-26 10:39 UTC, jakovmitrovski approved these changes

2024-07-30 13:51 UTC, themicp requested changes

2024-07-30 13:51 UTC, themicp commented on src/bin/l1_manager.rs
> +            .filter(|subnet| !subnet.has_required_validators())
Should not filter here, otherwise nobody can join after the minimum number of validators have already joined.

2024-08-05 20:12 UTC, OrestisAlpos commented on src/bin/l1_manager.rs
> +            .filter(|subnet| !subnet.has_required_validators())
Valid  comment, but  let's assume  for now that only one validator will want to join

2024-08-06 11:41 UTC, themicp commented on src/bin/l1_manager.rs
> +            .filter(|subnet| !subnet.has_required_validators())
We can just remove it since it doesn't serve any purpose, no need to accumulate code debt.

2024-08-07 16:49 UTC, OrestisAlpos commented on src/bin/l1_manager.rs
> +            .filter(|subnet| !subnet.has_required_validators())
Let's do that @jakovmitrovski . Let's allow users to always join.

2024-08-13 08:57 UTC, merged